[package]
name = "super-mastermind"
version = "0.1.0"
authors = ["quantumsheep <nathanael.dmc@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
rand = "0.8.0"
clap = "3.0.0-beta.2"
